### ISSUE TITLE
how to set CORS in v1.3.0

### ISSUE THREAD

**Issue by eelco2k** [code-chat-br/whatsapp-api#100]
The .env config for setting CORS is not available in 1.3.0 i did have it in version v1.2.6

in my env.yml file:
```

# Choose the server type for the application
SERVER:
  TYPE: http # https
  PORT: 8086 # 443

CORS:
  ORIGIN:
    - '*'
    # - yourdomain.com
  METHODS:
    - POST
    - GET
    - PUT
    - DELETE
  CREDENTIALS: true
```

i could set the CORS ORIGIN
